import { Darker_Grotesque } from "next/font/google";
const darker_grotesque = Darker_Grotesque({
  subsets: ["latin"],
  display: "swap",
  style: ["normal"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* social open graph content */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
        {/* <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:title" content="Green Leaf CMS" />
        <meta
          property="twitter:description"
          content="Show your menus in a screen instead of paper"
        />
        <meta
          property="twitter:image"
          content="https://res.cloudinary.com/dufn79tap/image/upload/v1702848517/Green%20Leaf%20CMS/v4hkk2azuxjxf1hqwcbn.jpg"
        />

        <meta property="og:title" content="Green Leaf CMS" />
        <meta
          property="og:description"
          content="Show your menus in a screen instead of paper"
        />
        <meta
          property="og:image"
          content="https://res.cloudinary.com/dufn79tap/image/upload/v1702848517/Green%20Leaf%20CMS/v4hkk2azuxjxf1hqwcbn.jpg"
        />
        <meta property="og:url" content="https://www.greenleafcms.com/" />

        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="../public/favicon.ico"
        /> */}
      </head>
      <body
        className={`${darker_grotesque.className} min-h-screen mx-auto  bg-primary-darker`}
      >
        {/* Header */}
        <main className="w-full h-full bg-primary-darker">{children}</main>
        {/* Footer */}
      </body>
    </html>
  );
}
